[package]
name = "ferry"
version = "0.1.0"
authors = ["Anders <git@anders.place>"]
edition = "2021"

[dependencies]
dioxus = { version = "0.7.3", features = ["desktop", "router"] }
surrealdb = { version = "=3.0.0-beta.3", features = ["kv-surrealkv"] }
surrealdb-types = "=3.0.0-beta.4"
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4", features = ["serde"] }
walkdir = "2"
thiserror = "2"
blake3 = "1"
plist = "1"
rfd = "0.15"
tracing = "0.1"
tracing-subscriber = "0.3.22"
tracing-appender = "0.2.4"

[dev-dependencies]
tempfile = "3"

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
